# Generated by Django 5.0.14 on 2025-09-12 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='data_solicitacao',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='admin_responsavel',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_resposta',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='usuario_alvo',
        ),
        migrations.AddField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(blank=True, choices=[('POS', 'POS PDV'), ('MINI PDV', 'Mini PDV'), ('TOTENS', 'Totens Desenvolvimento'), ('OUTROS', 'Outros Equipamentos'), ('HOME OU EVENTOS', 'Fora da POS')], default='Outros', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='posse_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_cedidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('pendente_aprovacao', 'Pendente de Aprovação do Admin'), ('pendente_confirmacao', 'Pendente de Confirmação do Par'), ('aprovada', 'Aprovada'), ('negada', 'Negada')], default='pendente_aprovacao', max_length=30),
        ),
    ]
